# Generated by Django 3.1.7 on 2021-09-02 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='locationX',
            new_name='latitude',
        ),
        migrations.RenameField(
            model_name='report',
            old_name='locationY',
            new_name='longitute',
        ),
        migrations.RemoveField(
            model_name='report',
            name='image',
        ),
        migrations.AlterField(
            model_name='report',
            name='floodLevel',
            field=models.FloatField(),
        ),
        migrations.CreateModel(
            name='Report_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='report.report')),
            ],
            options={
                'db_table': 'report_images',
            },
        ),
    ]
