# Generated by Django 3.1.7 on 2021-03-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterModelTable(
            name='report',
            table='report',
        ),
    ]
