# Generated by Django 3.1.7 on 2021-09-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20210902_1606'),
    ]

    operations = [
        migrations.RenameField(
            model_name='report',
            old_name='longitute',
            new_name='longitude',
        ),
    ]
