# Generated by Django 3.1.7 on 2021-03-16 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_report_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='floodLevel',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
