# Generated by Django 3.1.7 on 2021-09-02 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0003_auto_20210902_1641'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Report_Images',
            new_name='Report_Image',
        ),
    ]
