# Generated by Django 3.1.7 on 2021-09-10 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0005_reaction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='floodLevel',
            field=models.IntegerField(),
        ),
    ]
