# Generated by Django 3.1.7 on 2021-03-20 12:31

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FloodProneArea',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('water_volume', models.FloatField(default=0)),
                ('speed_to_subside', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_id', models.IntegerField(default=0)),
                ('w_temp', models.FloatField(default=0)),
                ('w_description', models.TextField()),
                ('w_icon', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locationX', models.FloatField()),
                ('locationY', models.FloatField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime.now)),
                ('image', models.ImageField(blank=True, upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FloodForecast',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=datetime.datetime.now)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.floodpronearea')),
                ('weather', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='forecast.weather')),
            ],
        ),
    ]
